apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-app
  namespace: deployment-flux-manifest
  labels:
    app: response-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: response-app
  template:
    metadata:
      labels:
        app: response-app
    spec:
      containers:
        - name: response-app
          imagePullPolicy: Always
          image: ghcr.io/francsco99/response-service:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
