apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: deployment-flux-manifest
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - name: http
      port:       80      # porta interna del Service
      targetPort: 8080   # mappa al containerPort 8080
      nodePort:   30081  # porta su cui esporre dal nodo
