apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-values-configmap
  namespace: deployment-flux-helm
data:
  values.yaml: |
    replicaCount: 2

    image:
      repository: ghcr.io/francsco99/hello-service
      tag: "latest"
      pullPolicy: Always

    service:
      type: NodePort
      port: 80
      targetPort: 8080
      nodePort: 30091

    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

    env:
      - name: RESPONSE_SERVICE_URL
        value: "http://response-service.deployment-flux-helm"

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

    namespace: deployment-flux-helm

    serviceAccount:
      create: true
      name: ""
      imagePullSecrets:
        - name: ghcr-secret

    ingress:
      enabled: false

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: null
    
