apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hello-service
  namespace: deployment-flux-helm
spec:
  interval: 5m
  chart:
    spec:
      chart: spring-helm-chart
      sourceRef:
        kind: HelmRepository
        name: my-charts
        namespace: flux-system
      version: ">=0.1.0"
  valuesFrom:
    - kind: ConfigMap
      name: hello-values-configmap
  targetNamespace: deployment-flux-helm
