apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-charts
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://ghcr.io/francsco99/spring-helm-chart
